done task_19
GeniusFromMinsk/taskmanager pull request #2
Opened 2024-07-05 12:32 UTC by GeniusFromMinsk

Добавил Model, DAO, Service, util, starter модули. Очень стыдно за starter, но не особо понимаю пока как его по другому написать(там просто тесты работы бд), функционал весь тестил, было без ошибок.

2024-07-11 13:28 UTC, Willynick commented
Конфликты нужно порешать. Если есть проблемы с решением конфликтов - может созвониться
![image](https://github.com/GeniusFromMinsk/taskmanager/assets/57830441/d7a89e06-0d35-418f-8249-f26638d653bb)

2024-07-11 13:51 UTC, Willynick requested changes

2024-07-11 13:51 UTC, Willynick commented on dao/pom.xml
> +    <url>http://maven.apache.org</url>
Убираем url отовсюду

2024-07-11 13:51 UTC, Willynick commented on dao/.gitignore
> +target/
Скрипты перенеси в модуль dao. В resource папке там просто создай папку sql и туда скрипты
![image](https://github.com/GeniusFromMinsk/taskmanager/assets/57830441/bb555b91-847c-4d60-8aa7-08a4fea5fe6a)

2024-07-11 13:51 UTC, Willynick commented on dao/.gitignore
> +target/
А src каталог вообще удалить из главного модуля

2024-07-11 13:51 UTC, Willynick commented on dao/.gitignore
> +### Eclipse ###
.gitignore файл оставляй только в родительском модуле
![image](https://github.com/GeniusFromMinsk/taskmanager/assets/57830441/cd6c9b6a-0c88-420e-8655-f4f5f3b61c04)

2024-07-11 13:51 UTC, Willynick commented on dao/src/test/java/com/itacademy/courses/AppTest.java
> +public class AppTest
Убираем везде сгенерированные тесты
![image](https://github.com/GeniusFromMinsk/taskmanager/assets/57830441/5b4793c5-9b48-47e5-9d38-62779ee7f746)

2024-07-11 13:51 UTC, Willynick commented on util/src/main/java/com/itacademy/courses/db/DBConnection.java
> +    private static final String JDBC_URL = "jdbc:postgresql://localhost:5432/manager";
Настроечки давай вынесем в отдельный файл

2024-07-11 13:51 UTC, Willynick commented on util/src/main/java/com/itacademy/courses/db/DBConnection.java
> +        return DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASSWORD);
Каждый раз будешь создавать Connection?)
Попахивает потерей производительности
![image](https://github.com/GeniusFromMinsk/taskmanager/assets/57830441/05fd7630-9770-4553-9852-63fe8458e302)

2024-07-11 13:51 UTC, Willynick commented on util/src/main/java/com/itacademy/courses/db/DBConnection.java
> +        return DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASSWORD);
Переделай на синглтон

2024-07-11 13:51 UTC, Willynick commented on starter/src/main/java/com/itacademy/courses/Main.java
> +        InsertApp application = new InsertApp();
Почему всё закомментировано? Пусть останется, правда не stackTrace, а логгирование

2024-07-11 13:51 UTC, Willynick commented on model/src/main/java/com/itacademy/courses/models/Category.java
> +    private Timestamp created_at;
Все в camelCase, в Java всегда и везде. Поменяй везде у себя

2024-07-11 13:51 UTC, Willynick commented on model/src/main/java/com/itacademy/courses/models/Category.java
> +    private int id;
Пустая строка после пятой строки. Применить так для всех классов

2024-07-11 13:51 UTC, Willynick commented on model/src/main/java/com/itacademy/courses/models/Category.java
> +    }
Пустая строка после 48 строки. Применить так ко всем другим классам

2024-07-11 13:51 UTC, Willynick commented on dao/src/main/java/com/itacademy/courses/dao/CategoryDAO.java
> +    private static final String INSERT_CATEGORY_SQL = "INSERT INTO Categories (name, description) VALUES (?, ?)";
Пиши уже в скриптах всё в верхнем регистре, так будет красиво. Т.е. CATEGORIES, NAME, DESCRIPTION и т.д.

2024-07-11 13:51 UTC, Willynick commented on dao/src/main/java/com/itacademy/courses/dao/CategoryDAO.java
> +    private void printSQLException(SQLException ex) {
Создай утилитный класс, который будет отлавливать разные ошибки и писать сообщение об ошибке

2024-07-11 13:51 UTC, Willynick commented on starter/src/main/java/com/itacademy/courses/InsertApp.java
> +        filter.setCriteria("status: completed");
Как ты потом будешь фильтровать по такой критерии? Продумай механизм, потому что фильтровать будешь ты. И по-хорошему тебе этот механизм нужно уже реализовать)

2024-07-11 13:51 UTC, Willynick commented on service/src/main/java/com/itacademy/courses/services/UserService.java
> +public class UserService {
Тебе нужно уже хотя бы наметить будущие методы, а не просто вызывать методы ДАО. Т.е. метод регистрации пользователя, метод логина пользователя и весь остальной функционал, что предусмотрено твоей задачей. Т.е. сделать какую-то несложную логику первоначальную. Потом уже можем дорабатывать

2024-07-19 11:43 UTC, Willynick requested changes

2024-07-19 11:43 UTC, Willynick commented on dao/src/main/java/com/itacademy/courses/dao/TaskDAO.java
> +        try (Connection connection = DBConnection.getInstance().getConnection();
У тебя может быть много фильтров. Давай их объединим в enum, где каждой константе енама будет соответствовать нужны SQL (часть SQL) запроса. Создай сервисный метод, который будет принимать значение енама и по нему филтровать

2024-07-19 11:43 UTC, Willynick commented on service/src/main/java/com/itacademy/courses/services/UserService.java
> +            if (userDAO.isUserExists(user.getEmail(), user.getUsername())) {
Убираем из всех классов stackTrace и заменяем на корректное логгирование

2024-07-19 11:43 UTC, Willynick commented on starter/src/main/java/com/itacademy/courses/InsertApp.java
> +        //createReportsForUser();
Приведи в порядок, удали ненужные комментарии и ненужные методы.

2024-07-21 11:51 UTC, GeniusFromMinsk commented on dao/src/main/java/com/itacademy/courses/dao/TaskDAO.java
> +        try (Connection connection = DBConnection.getInstance().getConnection();
Гениально хавхавхахва, реально лайк

2024-08-05 11:37 UTC, merged